server:
   port: 9002

spring:
   application:
      name: baitu-order-service
   jackson:
      time-zone: GMT+8
      serialization:
         fail-on-empty-beans: false
      date-format: yyyy-MM-dd HH:mm:ss
      
#服务描述
info:
   project:
      name: 订单服务
      version: 1.0.0

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost1:8761/eureka/,http://localhost2:8861/eureka/
   instance:
      #每隔5s心跳一次,证明本服务还活着
      lease-renewal-interval-in-second: 5
      #本服务10s内没有心跳,就将该服务从服务端剔除
      lease-expiration-duration-in-second: 10   