server:
   port: 10001

#注意： 页面的节点注册信息格式是：  主机名/ip :  ${spring.application.name} : ${server.port}

spring:
   application:
      name: baitu-eureka-peer1
   #开启重试机制
   cloud:
      loadbalancer:
         retry:
            enable: true 
 
info:
   project:
      name: project-eureka-peer1
      version: 1.0.0 

eureka:
   instance:
      hostname: 127.0.0.1
      preferIpAddress: true
   client: 
      serviceUrl:
         defaultZone: http://127.0.0.2:10001/eureka/
      #不向注册中心注册自己
      register-with-eureka: false
      #不需要去检索服务
      fetch-registry: false
      healthcheck: 
         enable: true
   #关闭eureka的自我保护机制
   server:
      enable-self-preservation: false
   
#订单服务进行配置
baitu-producer-order:
   ribbon:
      #请求连接的超时
      ConnectTimeout: 300   
      #请求处理的超时
      ReadTimeout: 1000
      #所操作请求都重试
      OkToRetryOnAllOperations: true
      #当前实例重试次数
      MaxAutoRetires: 2
      #切换实例重试次数
      MaxAutoRetriesNextServer: 2  