server:
  port: 8861
spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: localhost2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/
  server:
    enableSelfPreservation: false