server:
   port: 9000

spring:
   application:
      name: baitu-producer-user
   jackson:
      time-zone: GMT+8
      serialization:
         fail-on-empty-beans: false
      date-format: yyyy-MM-dd HH:mm:ss
      

info:
   project:
      name: project-producer-user
      version: 1.0.0

eureka:
   instance:
      hostname: 127.0.0.3
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/

      