server:
   port: 8000
   
spring:
   application:
      name: baitu-consumer-ribbon-record
   jackson:
      time-zone: GMT+8
      serialization:
         fail-on-empty-beans: false
      date-format: yyyy-MM-dd HH:mm:ss

info:
   project:
      name: project-ribbo-record
      version:  1.0.0
      

eureka:
   instance:
      name: 127.0.0.5
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/
         