server:
  port: 8761
spring:
  application:
    name: eurekaserver
  
eureka:
  instance:
    hostname: localhost1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost2:8861/eureka/
  server:
    enableSelfPreservation: false